### ISSUE TITLE
Searching Project taking too long

### ISSUE THREAD

**Issue by ramtinsoltani** [mrodalgaard/atom-todo-show#116] opened 2016-05-01 22:03 UTC
Searching shows `no results...` in `Projects` but it founds the correct result in `Open File`. After waiting a while is shows the results.

The thing is it doesn't show any loading/searching icon, and most importantly, it take too much time to find the result in a project containing only 4 markdown files.

**Comment by mrodalgaard** [comment] 2016-05-22 09:57
Hi @morbidgames, 1b95611b3cc78fc007f12840c9e9bb1ccfda924a fixes the missing loading spinner when switching scope before a search is finished. It will be available in the next release.

Regarding the slow scan. Internally the package is using the same mechanism as [find-and-replace](https://github.com/atom/find-and-replace) (though with a more complex regular expression). Is that also slow in your project? How big are those 4 markdown files and are there more files in subdirectories that are not ignored?

**Comment by morbidgames** [comment] 2016-05-23 09:20
Find and replace is super fast, and those markdown files are short (the bigest one has at last 80 lines).
Haven't checked the new update, if this is fixed in the update I'll close this thread.

**Comment by mrodalgaard** [comment] 2016-06-11 13:08
Strange that find-and-replace is instant while todo-show is slow. Because they mostly use the same mechanism underneath.

Any way to send me the project to reproduce?

**Comment by blacknred0** [comment] 2017-10-26 15:52
I see that this is closed, but I am experiencing the same issue.  What I see is that when I switch to project, the search path goes all of the way to the thousands, when I only have the one path and maybe a couple of folders.

I don't know if it makes a difference, but I am running this on an SD Card.  I get that it will be slow but still shouldn't see thousands of search paths when I only have one of two paths and couple of files.

**Comment by ramtinsoltani** [comment] 2017-10-27 06:04
Just want to mention that my issue is resolved. The search is super fast and only searches within the defined range (Project, Open Files, etc.)

**Comment by mrodalgaard** [comment] 2018-02-20 19:29
@ramtinsoltani super.

@blacknred0 do you still see the same issue. Are you sure the project root is as you expected and there are no hidden directories (starting with `.`) in your project?

**Closed by mrodalgaard** 2018-02-20 19:29 UTC

**Comment by blacknred0** [comment] 2018-02-22 01:24
@mrodalgaard this release seems to be a lot faster.  I think I could live with the results since is being read out of an SD Card I would expect some latency.  ...and yes, there are hidden directories, but not that many of the small projects that I've been using.
