### ISSUE TITLE
showing Found 5 results but not showing in table

### ISSUE THREAD

**Issue by vsagar9944** [mrodalgaard/atom-todo-show#128] opened 2016-07-19 17:49 UTC
When i open/refresh my todo list it is showing me that **"Found 5 results in workspace"** but in todo table it is showing no results
![todo_issue](https://cloud.githubusercontent.com/assets/8274701/16960455/45f67674-4e07-11e6-84bb-51b2bf5e0972.png)

**Comment by mrodalgaard** [comment] 2016-07-24 09:35
I am unable to reproduce this, so I need some more details:

1. Are you using the newest Atom and todo-show package?
2. Are the files with todos saved?
3. Are the debug console (View -> Developer -> Toggle Developer Tools) outputting any errors or warnings?
4. Can you attach/send the project (or a smaller example where this behaviour is also occurring) so I can try to reproduce?

**Comment by mrodalgaard** [comment] 2017-01-07 20:25
Cannot reproduce and missing feedback, so closing!

**Closed by mrodalgaard** 2017-01-07 20:25 UTC
